name: oneaction


on:
  push:
    branches-ignore:
      - main

  pull_request:
    branches:
      - dev

env:
    var1: "value1"

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "step1" > step1.txt
  job2:
    name: job2
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "step1"
  job3:
    name: job3
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "step1"
  job4:
    name: job4
    needs: job3
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "step1"
